import type { Metadata } from "next";

import {inter, geistMono, geistSans} from "@/./fonts/fonts"
import "../globals.css";



export const metadata: Metadata = {
  title: "Ecommerce-template-1",
  description: "Generated by create next app",
};

export default function NewAccount({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
