import type { Metadata } from "next";
import { inter, geistMono, geistSans } from "@/./fonts/fonts";
import "../globals.css";
import { SideBar, TopMenu } from "@/components";

export const metadata: Metadata = {
  title: "Ecommerce-template-1",
  description: "Generated by create next app",
};

export default function ShopLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <main>
          <TopMenu />
          <SideBar/>
          {children}
        </main>
      </body>
    </html>
  );
}
