import "./globals2.css";
import type { Metadata } from "next";
import { inter, geistMono, geistSans } from "@/fonts/fonts";
import { Provider } from "@/components";

export const metadata: Metadata = {
  title: "Ecommerce-template-1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>

        <>{children}</>
        </Provider>
      </body>
    </html>
  );
}
